apiVersion: v1
kind: Pod
metadata:
  name: redis-storage-leonid
  labels:
    app: redis-storage-leonid
spec:
  containers:
    - name: redis
      image: redis:alpine
      ports:
        - containerPort: 6379
      volumeMounts:
        - mountPath: /data/redis
          name: cache-volume
  volumes:
    - name: cache-volume
      emptyDir: {}