apiVersion: v1
kind: Pod
metadata:
  name: nginx-resolver
  labels:
    app: nginx-resovler
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-resolver-service
  labels:
    serv: nginx-resolver-service
spec:
  selector:
    app: nginx-resovler
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80