apiVersion: v1
kind: Pod
metadata:
  name: static-pod-nginx
  labels:
    app: static-pod-nginx
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      ports:
        - containerPort: 80

# cat <<EOF >/etc/kubernetes/manifests/static_pod.yaml
# apiVersion: v1
# kind: Pod
# metadata:
#   name: static-pod-nginx
#   labels:
#     app: static-pod-nginx
# spec:
#   containers:
#     - name: nginx
#       image: nginx:alpine
#       ports:
#         - containerPort: 80
# EOF