apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
  labels:
    app: multi-pod
spec:
  containers:
    - name: alpha
      image: nginx
      env:
        - name: alpha
    - name: beta
      image: busybox
      command: [ "/bin/sh", "-c", "--" ]
      args: [ "sleep 4800" ]
      env:
        - name: beta