---
apiVersion: v1
kind: Namespace
metadata:
  name: finance-leonid
  labels:
    ns-name: finance-leonid
---
apiVersion: v1
kind: Pod
metadata:
  name: temp-bus
  namespace: finance-leonid
  labels:
    app: temp-bus
spec:
  containers:
    - name: redis
      image: redis:alpine
      ports:
        - containerPort: 6379
